//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.BookShop.WebServiceDemo.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldResponse HelloWorld(CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldResponse> HelloWorldAsync(CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetUserInfoListResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInfoList", ReplyAction="*")]
        CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListResponse GetUserInfoList(CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInfoList", ReplyAction="*")]
        System.Threading.Tasks.Task<CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListResponse> GetUserInfoListAsync(CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfoList", Namespace="http://tempuri.org/", Order=0)]
        public CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListRequestBody Body;
        
        public GetUserInfoListRequest() {
        }
        
        public GetUserInfoListRequest(CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUserInfoListRequestBody {
        
        public GetUserInfoListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfoListResponse", Namespace="http://tempuri.org/", Order=0)]
        public CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListResponseBody Body;
        
        public GetUserInfoListResponse() {
        }
        
        public GetUserInfoListResponse(CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInfoListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserInfoListResult;
        
        public GetUserInfoListResponseBody() {
        }
        
        public GetUserInfoListResponseBody(string GetUserInfoListResult) {
            this.GetUserInfoListResult = GetUserInfoListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : CZBK.BookShop.WebServiceDemo.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<CZBK.BookShop.WebServiceDemo.ServiceReference1.WebService1Soap>, CZBK.BookShop.WebServiceDemo.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldResponse CZBK.BookShop.WebServiceDemo.ServiceReference1.WebService1Soap.HelloWorld(CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldRequest inValue = new CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldRequest();
            inValue.Body = new CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldRequestBody();
            CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldResponse retVal = ((CZBK.BookShop.WebServiceDemo.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldResponse> CZBK.BookShop.WebServiceDemo.ServiceReference1.WebService1Soap.HelloWorldAsync(CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldRequest inValue = new CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldRequest();
            inValue.Body = new CZBK.BookShop.WebServiceDemo.ServiceReference1.HelloWorldRequestBody();
            return ((CZBK.BookShop.WebServiceDemo.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListResponse CZBK.BookShop.WebServiceDemo.ServiceReference1.WebService1Soap.GetUserInfoList(CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListRequest request) {
            return base.Channel.GetUserInfoList(request);
        }
        
        public string GetUserInfoList() {
            CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListRequest inValue = new CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListRequest();
            inValue.Body = new CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListRequestBody();
            CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListResponse retVal = ((CZBK.BookShop.WebServiceDemo.ServiceReference1.WebService1Soap)(this)).GetUserInfoList(inValue);
            return retVal.Body.GetUserInfoListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListResponse> CZBK.BookShop.WebServiceDemo.ServiceReference1.WebService1Soap.GetUserInfoListAsync(CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListRequest request) {
            return base.Channel.GetUserInfoListAsync(request);
        }
        
        public System.Threading.Tasks.Task<CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListResponse> GetUserInfoListAsync() {
            CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListRequest inValue = new CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListRequest();
            inValue.Body = new CZBK.BookShop.WebServiceDemo.ServiceReference1.GetUserInfoListRequestBody();
            return ((CZBK.BookShop.WebServiceDemo.ServiceReference1.WebService1Soap)(this)).GetUserInfoListAsync(inValue);
        }
    }
}
